### ISSUE TITLE
Install with Python 3.11 fails

### ISSUE THREAD

**Issue by CarrieFilion** [athob/py-ananke#1]
I'm attempting to install py-ananke on my local machine (M2 Mac, OS 13.4, Python 3.11) and the install fails when attempting to build wheels for vaex-core. It seems that vaex-core may not yet support Python 3.11 (see e.g. https://github.com/vaexio/vaex/pull/2331) - perhaps it is best to require Python versions earlier than 3.11 in the py-ananke install until vaex-core fully supports 3.11

**Comment by athob** [comment]
Thanks for noticing this! I'll add that requirement in the next release

**Comment by athob** [comment]
Requirement was included in the newest release [v0.1.0-beta2](https://github.com/athob/py-ananke/releases/tag/v0.1.0-beta2)
